# This is a basic workflow to help you get started with Actions

name: gh-pages
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build
    - name: Change base-tag in index.html from / to portifolio
      run: sed -i 's/<base href="\/" \/>/<base href="\/portifolio\/" \/>/g' build/wwwroot/index.html
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/wwwroot
